filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /var/log/apache2/access.log
      - /var/log/apache2/error.log

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
