filebeat.inputs:
  - type: filestream
    id: apache-postgres-logs
    enabled: true
    paths:
      - /var/log/apache2/access.log
      - /var/log/apache2/error.log
      - /var/log/postgresql/postgresql.log
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after

  - type: filestream
    id: ufw-logs
    enabled: true
    paths:
      - /var/log/ufw.log
      - /var/log/kern.log
    fields:
      log_type: firewall_ufw
      service: ufw
    fields_under_root: true

  - type: syslog
    protocol.udp:
      host: "0.0.0.0:514"
    format: auto
    tags: ["syslog"]

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
