
input {
  tcp {
    port => 6000
    codec => json
    tags => ["ansible"]
  }
}

filter {
  if "ansible" in [tags] {
    mutate {
      add_field => { "[@metadata][source]" => "ansible" }
    }
  }
}

output {
  if "ansible" in [tags] {
    
    opensearch {
      hosts => ["https://opensearch:9200"]
      user => "admin"
      password => "YourStrongSuperPassword123!"
      index => "ansible-%{+YYYY.MM.dd}"
      ssl => true
      ssl_certificate_verification => false
      ecs_compatibility => disabled
    cacert => "/usr/share/logstash/config/certs/ca.pem"

      manage_template => false
    }
  }
}