input {
  beats {
    port => 5044
  }
  syslog {
    port => 5000
  }
}

output {
  opensearch {
    hosts => ["https://opensearch:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
    user => "admin"
    password => "YourStrongSuperPassword123!"
    
    # SSL Configuration
    ssl => true
    # ssl_certificate_verification => false
    # Alternatively, for proper SSL verification:
    ssl_certificate_verification => true
    cacert => "/usr/share/logstash/config/certs/ca.pem"
  }
}