input {
  beats {
    port => 5044
  }
}

output {
  opensearch {
    hosts => ["https://opensearch:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
    user => "admin"
    password => "YourStrongSuperPassword123!"
    ssl => true
    ssl_certificate_verification => true
    cacert => "/usr/share/logstash/config/certs/ca.pem"
      manage_template => false 
    ecs_compatibility => disabled
  }
}