input {
  beats {
    port => 5044
  }
}

filter {
  if [host][name] {
    mutate {
      add_field => { "hostname" => "%{[host][name]}" }
      remove_field => [ "host" ]
      add_field => { "host" => "%{hostname}" }
      remove_field => [ "hostname" ]
    }
  }
}

output {
  opensearch {
    hosts => ["https://opensearch:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
    user => "admin"
    password => "YourStrongSuperPassword123!"
    ssl => true
    ssl_certificate_verification => true
    cacert => "/usr/share/logstash/config/certs/ca.pem"
    manage_template => false 
    ecs_compatibility => disabled
  }
}