
services:
  opensearch:
    image: opensearchproject/opensearch:3.0.0
    container_name: opensearch
    environment:
      - node.name=opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=YourStrongSuperPassword123!"
      # SSL Configuration
      - "plugins.security.ssl.transport.pemcert_filepath=certs/opensearch.pem"
      - "plugins.security.ssl.transport.pemkey_filepath=certs/opensearch-key.pem"
      - "plugins.security.ssl.transport.pemtrustedcas_filepath=certs/ca.pem"
      - "plugins.security.ssl.transport.enforce_hostname_verification=false"
      - "plugins.security.ssl.http.enabled=true"
      - "plugins.security.ssl.http.pemcert_filepath=certs/opensearch.pem"
      - "plugins.security.ssl.http.pemkey_filepath=certs/opensearch-key.pem"
      - "plugins.security.ssl.http.pemtrustedcas_filepath=certs/ca.pem"
      - "plugins.security.allow_default_init_securityindex=true"
      - "plugins.security.authcz.admin_dn=CN=admin,OU=IT,O=MyOrg,L=San Francisco,ST=CA,C=US"
      - "plugins.security.nodes_dn=CN=opensearch,OU=IT,O=MyOrg,L=San Francisco,ST=CA,C=US"
      - "plugins.security.audit.type=internal_opensearch"
      - "plugins.security.enable_snapshot_restore_privilege=true"
      - "plugins.security.check_snapshot_restore_write_privileges=true"
      - "plugins.security.restapi.roles_enabled=[\"all_access\", \"security_rest_api_access\"]"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ../certs:/usr/share/opensearch/config/certs:ro
    ports:
      - 9200:9200
    networks:
      - elk-net

  dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0
    container_name: opensearch-dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["https://opensearch:9200"]'
      - "OPENSEARCH_USERNAME=admin"
      - "OPENSEARCH_PASSWORD=YourStrongSuperPassword123!"
      - "OPENSEARCH_DASHBOARDS_SMTP_ENABLED=true"
      - "OPENSEARCH_DASHBOARDS_SMTP_HOST=smtp-relay"
      - "OPENSEARCH_DASHBOARDS_SMTP_PORT=25"
      - "OPENSEARCH_DASHBOARDS_SMTP_SECURE=false"
      - "OPENSEARCH_DASHBOARDS_SMTP_FROM=<INSERT MAIL>"
      - "SERVER_SSL_ENABLED=true"
      - "SERVER_SSL_CERTIFICATE=/usr/share/opensearch-dashboards/config/certs/opensearch.pem"
      - "SERVER_SSL_KEY=/usr/share/opensearch-dashboards/config/certs/opensearch-key.pem"
    volumes:
      - ../certs:/usr/share/opensearch-dashboards/config/certs:ro
    ports:
      - 5601:5601
    depends_on:
      - opensearch
      - smtp-relay
    networks:
      - elk-net

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:8.9.0
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ../certs:/usr/share/logstash/config/certs:ro
    depends_on:
      - opensearch
    ports:
      - 5044:5044
      - 6000:6000
      - 9600:9600
    networks:
      - elk-net

  smtp-relay:
    image: bytemark/smtp:latest
    container_name: smtp-relay
    restart: always
    environment:
      - RELAY_HOST=smtp.gmail.com
      - RELAY_PORT=587
      - RELAY_USERNAME=<INSERT YOUR EMAIL>
      - RELAY_PASSWORD=<INSERT YOUR PASSWORD>
      - MAILNAME=yourdomain.local
    ports:
      - "25:25"
    networks:
      - elk-net

volumes:
  opensearch-data:

networks:
  elk-net:
    driver: bridge