filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/system.log
      - /var/log/install.log

output.logstash:
  hosts: ["localhost:5044"]

setup.template.enabled: false
setup.ilm.enabled: false

logging.level: info
