
services:
  apache:
    image: php:8.2-apache
    container_name: apache-server
    volumes:
      - ./www:/var/www/html
      - apache-logs:/var/log/apache2
    ports:
      - "8080:80"
    networks:
      - external-net
      - elk-stack_elk-net
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
      - ./postgres/postgresql.conf:/etc/postgresql/custom-postgresql.conf
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/etc/postgresql/custom-postgresql.conf"]

  filebeat:
    container_name: filebeat-agent
    image: elastic/filebeat:9.0.1
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - apache-logs:/var/log/apache2:ro
      - postgres-logs:/var/log/postgresql:ro
    networks:
      - elk-stack_elk-net
      - external-net
    depends_on:
      - apache

volumes:
  postgres-logs:
  postgres-data:
  apache-logs:

networks:
  external-net:
    driver: bridge
  elk-stack_elk-net:
    external: true  # assumes ELK stack created this
