
services:
  syslog-ubuntu:
    image: ubuntu:22.04
    container_name: syslog-ubuntu
    volumes:
      - syslog-etc:/etc
    command: >
      sh -c "apt update && apt install -y rsyslog &&
      echo '. @filebeat-agent:514' >> /etc/rsyslog.conf &&
      echo '#module(load=\"imklog\")' > /etc/rsyslog.d/00-disable-imklog.conf &&
      rsyslogd -n"
    networks:
      - elk-stack_elk-net
    depends_on:
      - filebeat

  apache:
    image: php:8.2-apache
    container_name: apache-server
    volumes:
      - ./www:/var/www/html
      - ./apache-logs:/var/log/apache2
    ports:
      - "8080:80"
    networks:
      - external-net
      - elk-stack_elk-net
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
      - ./postgres/postgresql.conf:/etc/postgresql/custom-postgresql.conf
      - ./postgres:/scripts
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/etc/postgresql/custom-postgresql.conf"]

  filebeat:
    container_name: filebeat-agent
    image: elastic/filebeat:9.0.1
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./apache-logs:/var/log/apache2:ro
      # - /var/log/ufw.log:/var/log/ufw.log:ro
      # - /var/log/kern.log:/var/log/kern.log:ro
      - postgres-logs:/var/log/postgresql:ro
    networks:
      - elk-stack_elk-net
      - external-net
    depends_on:
      - apache

  auditbeat:
    image: docker.elastic.co/beats/auditbeat:8.9.0
    container_name: auditbeat
    user: root
    cap_add: ["AUDIT_CONTROL","AUDIT_READ"]
    volumes:
      - ./auditbeat/auditbeat.yml:/usr/share/auditbeat/auditbeat.yml:ro
      - syslog-etc:/hostfs/etc:ro
      - ../certs/ca.pem:/usr/share/auditbeat/certs/ca.pem:ro
    networks:
      - elk-stack_elk-net
      - external-net
    depends_on:
      - syslog-ubuntu

volumes:
  postgres-logs:
  postgres-data:
  syslog-etc:

networks:
  external-net:
    driver: bridge
  elk-stack_elk-net:
    external: true  # assumes ELK stack created this
